name: SvalbardSurges
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - geopandas
  - pandas
  - netcdf4
  - matplotlib
  - rasterio
  - pathlib
  - numpy
  - sklearn
  - pip:
    - variete
